# netlify.toml (at repo root)
[build]
  base    = "gtfs-builder"   # folder that contains index.html & package.json
  command = "npm ci && npm run build"
  publish = "dist"           # <-- publish is relative to base, so use "dist" (not gtfs-builder/dist)

[build.environment]
  NODE_VERSION = "20.19.0"   # Vite 7 + plugin-react 5 require >=20.19