[build]
  base    = "gtfs-builder"        # folder with index.html + package.json
  command = "npm ci && npm run build"
  publish = "dist"                # publish is relative to base

[build.environment]
  NODE_VERSION = "20.19.0"        # Vite 7 / plugin-react 5 need >= 20.19